server:
  port: 8803
  error:
    include-message: always
spring:
  datasource:
    username: system
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521:booksales
    driver-class-name: oracle.jdbc.OracleDriver
mybatis-plus:
  type-enums-package: com.example.oracledemo.enmus
  type-aliases-package: com.example.oracledemo.pojo
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
  # id 自增长
  global-config:
    db-config:
      id-type: auto